name: Testing pipeline

# This action works with pull requests and pushes
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

  prettier:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch dependencies
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          prettier_options: --check **/*.{js,ts,tsx}
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

  esLint:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch dependencies
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: ESLint
        run: npx eslint "**/*.{js,ts,tsx}" --max-warnings=0
