name: Testing pipeline
run-name: Testing new changes...

# This action works with pull requests and pushes to main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

  prettier:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch dependencies
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Prettier
        run: npm run test:prettier

  eslint:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch dependencies
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: ESLint
        run: npm run test:eslint

  unit:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch dependencies
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Setup environment variables
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: echo $ENV_FILE | base64 -d > .env

      - name: Unit Tests
        run: npm run test:unit

  e2e:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch dependencies
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Setup environment variables
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: echo $ENV_FILE | base64 -d > .env

      - name: E2E Tests
        run: npm run test:e2e
